name: "mini_dbt_project"
version: "1.0.0"
config-version: 2

profile: mini-dbt-project-profile

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"

models:
  mini_dbt_project:
    staging:
      +materialized: view
